### ISSUE TITLE
semantic-release-monorepo is updateing the version of both apps when only one app was updated.

### ISSUE THREAD

**Issue by IdecEddy** [pmowrer/semantic-release-monorepo#124]
Hello, 

I am using terborepo to manage my monorepo. I made a change to a file in one of the packages in my monorepo ( `app1-express` ). When the semantic-release step ran in my GitLab CI/CD it released both apps and raised the version number in both of the apps. I ran yarn semantic-release in both app1-express and app2-nextjs directory. 

**Tree of my project's apps dir**
```
.
├── app1-express
│   ├── CHANGELOG.md
│   ├── docker
│   ├── index.ts
│   ├── node_modules
│   ├── package.json
│   ├── tsconfig.json
│   └── yarn-error.log
└── app2-nextjs
    ├── CHANGELOG.md
    ├── README.md
    ├── components
    ├── context
    ├── data
    ├── docker
    ├── manifests
    ├── next-env.d.ts
    ├── next.config.js
    ├── node_modules
    ├── out
    ├── package-lock.json
    ├── package.json
    ├── pages
    ├── public
    ├── server
    ├── styles
    ├── tsconfig.json
    ├── yarn-error.log
    └── yarn.lock
```

**what my releaserc.json**
```
{
  "branches": [
      "release",
      "master"
  ],
  "tagFormat": "app2-express/v${version}",
  "extends": "semantic-release-monorepo",
  "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
          "@semantic-release/changelog",
          {
              "changelogFile": "CHANGELOG.md"
          }
      ],
      [
          "@semantic-release/npm",
          {
              "npmPublish": false
          }
      ],
      [
          "@semantic-release/git",
          {
              "assets": [
                  "package.json",
                  "CHANGELOG.md"
              ],
              "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
          }
      ],
      [
          "@semantic-release/gitlab",
          {
              "gitlabUrl": "https://gitlab.com",
              "assets": []
          }
      ],
      [
          "@semantic-release/exec",
          {
              "publishCmd": "docker build stuff and docker push stuff here. "
          }
      ]
  ]
}
```

**Gitlab CICD config**
```
publish:
  stage: release
  image: docker:latest
  cache:
    key: node_modules_nextjs
    paths:
      - apps/iqnox-nextjs/node_modules
      - apps/iqnox-express/node_modules
      - node_modules
    policy: pull
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - apk add git yarn --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
    - echo "unsafe-perm = true" >> ~/.npmrc
  script:
    - cd apps/app1-nextjs
    - yarn release
    - cd ../app2-express
    - yarn release 
  artifacts:
    reports:
      dotenv: apps/app1-nextjs/build.env
  only:
    refs:
      - master
```
yarn release looks like this in package.json script:  `"release": "yarn semantic-release"` 

I am not sure if semantic-release-monorepo would affect the `"@semantic-release/npm",` plugin that updates the package version. Can you provide any guidance on this topic?
