### ISSUE TITLE
Cannot make it work!!!

### ISSUE THREAD

**Issue by juliolmuller** [pmowrer/semantic-release-monorepo#173]
Friends of this community,

The idea behind this tool is great! Hoever, the documentation doesn't make it cler how to setup and how it works under the hood, so I'm failing to run it in my application project. NOTE: it's not an NPM library, but a backend and a frontend of an application.

View the package in branch `fff` gere: [juliolmuller/feedget](https://github.com/juliolmuller/feedget/tree/fff)

GitHub Actions workflow runs successfully but with the message "_There are no relevant changes, so no new version is released._". 

![Image](https://github.com/user-attachments/assets/b3c86ba2-d8a4-4b75-b2bc-7cbdd0e41619)

Here is my `.releaserc` file:

```json
{
  "branches": ["fff"],
  "extends": "semantic-release-monorepo",
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "conventionalcommits",
        "releaseRules": [...]
      }
    ],
    [
      "@semantic-release/release-notes-generator",
      {
        "preset": "conventionalcommits"
      }
    ],
    "@semantic-release/npm",
    [
      "@semantic-release/git",
      {
        "assets": "package.json",
        "message": "chore: deploy ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ],
    "@semantic-release/github"
  ]
}
```

...and here is my GH Actions workflow:

```yml
name: Release

on:
  push:
    branches:
      - fff

env:
  BUN_VERSION: latest
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Create release
        run: bun run release
```
