### ISSUE TITLE
ERR_INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by paulpach** [pmowrer/semantic-release-monorepo#91]
```
[7:16:25 PM] [semantic-release] [[Function: semantic-release-monorepo]] › ℹ  Found 0 commits for package root since last release

[7:16:25 PM] [semantic-release] [[Function: semantic-release-monorepo]] › ℹ  Analysis of 0 commits complete: no release

[7:16:25 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "[Function: semantic-release-monorepo]"

[7:16:25 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: semantic-release-monorepo]"

[7:16:25 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "[Function: semantic-release-monorepo]"

[7:16:25 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: semantic-release-monorepo]"

[7:16:25 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "[Function: semantic-release-monorepo]"

[7:16:25 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "[Function: semantic-release-monorepo]"

[7:16:25 PM] [semantic-release] › ✖  Failed step "analyzeCommits" of plugin "[Function: semantic-release-monorepo]"

[7:16:25 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object

    at validateString (internal/validators.js:112:11)

    at Module.require (internal/modules/cjs/loader.js:842:3)

    at require (internal/modules/cjs/helpers.js:74:18)

    at semantic-release-monorepo (/opt/apps/partitioned-node/partition-1/fc77c055/workspace/_Excellence_runway_runway_semver/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:41:24)

    at validator (/opt/apps/partitioned-node/partition-1/fc77c055/workspace/_Excellence_runway_runway_semver/node_modules/semantic-release/lib/plugins/normalize.js:34:30)

    at /opt/apps/partitioned-node/partition-1/fc77c055/workspace/_Excellence_runway_runway_semver/node_modules/semantic-release/lib/plugins/pipeline.js:37:40

    at next (/opt/apps/partitioned-node/partition-1/fc77c055/workspace/_Excellence_runway_runway_semver/node_modules/semantic-release/node_modules/p-reduce/index.js:17:9)

    at processTicksAndRejections (internal/process/task_queues.js:93:5) {

  code: 'ERR_INVALID_ARG_TYPE',

  pluginName: '[Function: semantic-release-monorepo]'

}

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type object

    at validateString (internal/validators.js:112:11)

    at Module.require (internal/modules/cjs/loader.js:842:3)

    at require (internal/modules/cjs/helpers.js:74:18)

    at semantic-release-monorepo (/opt/apps/partitioned-node/partition-1/fc77c055/workspace/_Excellence_runway_runway_semver/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:41:24)

    at validator (/opt/apps/partitioned-node/partition-1/fc77c055/workspace/_Excellence_runway_runway_semver/node_modules/semantic-release/lib/plugins/normalize.js:34:30)

    at /opt/apps/partitioned-node/partition-1/fc77c055/workspace/_Excellence_runway_runway_semver/node_modules/semantic-release/lib/plugins/pipeline.js:37:40

    at next (/opt/apps/partitioned-node/partition-1/fc77c055/workspace/_Excellence_runway_runway_semver/node_modules/semantic-release/node_modules/p-reduce/index.js:17:9)

    at processTicksAndRejections (internal/process/task_queues.js:93:5) {

  code: 'ERR_INVALID_ARG_TYPE',

  pluginName: '[Function: semantic-release-monorepo]'

}error Command failed with exit code 1.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

script returned exit code 1
```

Here is my release file:
```
extends: "semantic-release-monorepo"
branches: 
    - master
    - semver
plugins:
    - "@semantic-release/commit-analyzer"
    - "@semantic-release/release-notes-generator"
    - "@semantic-release/changelog"
    - "@semantic-release/npm"
    - "@semantic-release/git"
    - - "@semantic-release/github":
        githubUrl: https://ghe.aa.com,
        githubApiPathPrefix: 'api/v3'

          
```

**Comment by pmowrer** [comment]
Hi @paulpach! What versions of the `semantic-release-monorepo` and each of the plugins are you running?

**Comment by pmowrer** [comment]
Closing due to inactivity. Feel free to reopen if you have more information

**Comment by devtribe** [comment]
Hi,

i got the same error at my project. The release File is quite minimalistic

```yml
branches:
  - name: main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
```

The version are the newest. Just installed it.
Thanks

The Error 
```
[3:46:26 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:120:11)
    at Module.require (internal/modules/cjs/loader.js:896:3)
    at require (internal/modules/cjs/helpers.js:74:18)
    at semantic-release-monorepo (/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:41:24)
    at validator (.config/yarn/global/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at /.config/yarn/global/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (/.config/yarn/global/node_modules/p-reduce/index.js:17:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE',
  pluginName: '[Function: semantic-release-monorepo]'
}
TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received an instance of Object
    at validateString (internal/validators.js:120:11)
    at Module.require (internal/modules/cjs/loader.js:896:3)
    at require (internal/modules/cjs/helpers.js:74:18)
    at semantic-release-monorepo (/projects/aoe/congstar/ci/microservice-deployment/node_modules/semantic-release-plugin-decorators/src/wrapStep.js:41:24)
    at validator (/.config/yarn/global/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
    at /.config/yarn/global/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
    at next (/.config/yarn/global/node_modules/p-reduce/index.js:17:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE',
  pluginName: '[Function: semantic-release-monorepo]'
}
```

**Comment by pmowrer** [comment]
Hi @devtribe,

Sorry to hear you're running into issues. Unfortunately, I wasn't able to reproduce using the config you provided. The error (which should be improved) suggests you have an invalid config - is it possible there's another conflicting config in your setup (perhaps under the `release` key in `package.json` or [one of the other ways configs can be setup](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#configuration))?

**Comment by devtribe** [comment]
Hi,

you're right, SR used another `.releaserc`. 

But i got the same error if i use `@semantic-release/exec` together with `semantic-release-monorepo` :(
I want to generate a Changelog for my Monorepo without the publishing step

Here is my config:

```yaml
branches:
  - name: main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - path: "@semantic-release/exec"
    generateNotesCmd: "echo \"${nextRelease.notes}\" > CHANGELOG.md"
```

**Comment by pmowrer** [comment]
This configuration doesn't look valid to me - looks like a mix of the old a new semantic-release config formats. Please refer to the semantic-release docs on plugin configuration: https://semantic-release.gitbook.io/semantic-release/usage/plugins#plugins

You probably want something like this:

```yml
branches:
  - name: main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - generateNotesCmd: "echo \"${nextRelease.notes}\" > CHANGELOG.md"
```
